// AUTO-GENERATED by scripts/scan_thumbnails.py — do not edit by hand.
// Re-run the script after adding, removing, or renaming thumbnails.
var THUMBS = [
  {
    "file": "lowres/balloon/Balloon 2.png",
    "game": "balloon",
    "name": "Balloon 2",
    "color": "black",
    "colors": [
      "black",
      "white",
      "purple"
    ],
    "hex": "#073b6c"
  },
  {
    "file": "lowres/balloon/Winterpixel-Balloon.png",
    "game": "balloon",
    "name": "Winterpixel Balloon",
    "color": "black",
    "colors": [
      "black",
      "white",
      "red"
    ],
    "hex": "#002242"
  },
  {
    "file": "lowres/bigbattlemini/big battle mini.png",
    "game": "bigbattlemini",
    "name": "Big Battle Mini",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#4797c7"
  },
  {
    "file": "lowres/bigbattlemini/BigBattleMini-opening gatchas.png",
    "game": "bigbattlemini",
    "name": "Bigbattlemini Opening Gatchas",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "purple"
    ],
    "hex": "#2673e9"
  },
  {
    "file": "lowres/bigbattlemini/rarest item in big battle mini.png",
    "game": "bigbattlemini",
    "name": "Rarest Item In Big Battle Mini",
    "color": "black",
    "colors": [
      "black",
      "orange",
      "brown"
    ],
    "hex": "#030810"
  },
  {
    "file": "lowres/bobble/bobble thumbnail.png",
    "game": "bobble",
    "name": "Bobble Thumbnail",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "brown"
    ],
    "hex": "#33bee1"
  },
  {
    "file": "lowres/broski/broski thumbnail 2.png",
    "game": "broski",
    "name": "Broski Thumbnail 2",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "brown"
    ],
    "hex": "#c7eaef"
  },
  {
    "file": "lowres/broski/broski thumbnail.png",
    "game": "broski",
    "name": "Broski Thumbnail",
    "color": "white",
    "colors": [
      "white",
      "black",
      "gray"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/gd/EveryGooberDashSecret.png",
    "game": "gd",
    "name": "Everygooberdashsecret",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "gray"
    ],
    "hex": "#003d8a"
  },
  {
    "file": "lowres/gd/goober dash gameplay.png",
    "game": "gd",
    "name": "Goober Dash Gameplay",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "purple"
    ],
    "hex": "#0caefb"
  },
  {
    "file": "lowres/gd/GooberDashBest.png",
    "game": "gd",
    "name": "Gooberdashbest",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "pink"
    ],
    "hex": "#51cdf3"
  },
  {
    "file": "lowres/gd/GooberDashSpeedrunning.png",
    "game": "gd",
    "name": "Gooberdashspeedrunning",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "purple"
    ],
    "hex": "#0ab8fd"
  },
  {
    "file": "lowres/gd/MoreGooberDashSpeedrunning.png",
    "game": "gd",
    "name": "Moregooberdashspeedrunning",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "purple"
    ],
    "hex": "#11bafc"
  },
  {
    "file": "lowres/gd/UltimateGooberDashGuide.png",
    "game": "gd",
    "name": "Ultimategooberdashguide",
    "color": "white",
    "colors": [
      "white",
      "brown",
      "blue"
    ],
    "hex": "#b2c0c0"
  },
  {
    "file": "lowres/gooberroyale/goober royale.png",
    "game": "gooberroyale",
    "name": "Goober Royale",
    "color": "green",
    "colors": [
      "green",
      "black",
      "blue"
    ],
    "hex": "#327261"
  },
  {
    "file": "lowres/gooberworld/goober world.png",
    "game": "gooberworld",
    "name": "Goober World",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "purple"
    ],
    "hex": "#eea4f0"
  },
  {
    "file": "lowres/moonrockminers/moonrock miners guide.png",
    "game": "moonrockminers",
    "name": "Moonrock Miners Guide",
    "color": "white",
    "colors": [
      "white",
      "black",
      "blue"
    ],
    "hex": "#feffff"
  },
  {
    "file": "lowres/moonrockminers/moonrock miners guide2.png",
    "game": "moonrockminers",
    "name": "Moonrock Miners Guide2",
    "color": "white",
    "colors": [
      "white",
      "black",
      "gray"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/moonrockminers/moonrock miners thumbnail.png",
    "game": "moonrockminers",
    "name": "Moonrock Miners Thumbnail",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#409bd1"
  },
  {
    "file": "lowres/moonrockminers/moonrock miners thumbnail2.png",
    "game": "moonrockminers",
    "name": "Moonrock Miners Thumbnail2",
    "color": "white",
    "colors": [
      "white",
      "black",
      "gray"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/other/mag new site 1000th video.png",
    "game": "other",
    "name": "Mag New Site 1000th Video",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "gray"
    ],
    "hex": "#7a4b4f"
  },
  {
    "file": "lowres/other/mag new site.png",
    "game": "other",
    "name": "Mag New Site",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "gray"
    ],
    "hex": "#652f35"
  },
  {
    "file": "lowres/other/Meta quest thumbnail.png",
    "game": "other",
    "name": "Meta Quest Thumbnail",
    "color": "white",
    "colors": [
      "white",
      "gray"
    ],
    "hex": "#a6b8ec"
  },
  {
    "file": "lowres/other/pendel-Egg Saga MMORPG.png",
    "game": "other",
    "name": "Pendel Egg Saga Mmorpg",
    "color": "white",
    "colors": [
      "white",
      "gray",
      "brown"
    ],
    "hex": "#fafefc"
  },
  {
    "file": "lowres/projectgatherwood/Grinding Level 50 in gatherwood.png",
    "game": "projectgatherwood",
    "name": "Grinding Level 50 In Gatherwood",
    "color": "black",
    "colors": [
      "black",
      "white",
      "green"
    ],
    "hex": "#050c13"
  },
  {
    "file": "lowres/projectgatherwood/project gatherwood fishing 2.png",
    "game": "projectgatherwood",
    "name": "Project Gatherwood Fishing 2",
    "color": "black",
    "colors": [
      "black",
      "green",
      "white"
    ],
    "hex": "#1c4537"
  },
  {
    "file": "lowres/projectgatherwood/project gatherwood fishing.png",
    "game": "projectgatherwood",
    "name": "Project Gatherwood Fishing",
    "color": "blue",
    "colors": [
      "blue",
      "green",
      "gray"
    ],
    "hex": "#0565a0"
  },
  {
    "file": "lowres/projectgatherwood/project gatherwood.png",
    "game": "projectgatherwood",
    "name": "Project Gatherwood",
    "color": "gray",
    "colors": [
      "gray",
      "green",
      "black"
    ],
    "hex": "#b4ce9a"
  },
  {
    "file": "lowres/rbr/100Hours.png",
    "game": "rbr",
    "name": "100hours",
    "color": "red",
    "colors": [
      "red",
      "brown",
      "gray"
    ],
    "hex": "#b13a32"
  },
  {
    "file": "lowres/rbr/100Hours2.png",
    "game": "rbr",
    "name": "100hours2",
    "color": "red",
    "colors": [
      "red",
      "blue",
      "white"
    ],
    "hex": "#be4037"
  },
  {
    "file": "lowres/rbr/100SubsMontage.png",
    "game": "rbr",
    "name": "100subsmontage",
    "color": "red",
    "colors": [
      "red",
      "brown",
      "white"
    ],
    "hex": "#f20205"
  },
  {
    "file": "lowres/rbr/100SubsMontage2.png",
    "game": "rbr",
    "name": "100subsmontage2",
    "color": "black",
    "colors": [
      "black",
      "red",
      "white"
    ],
    "hex": "#4a0212"
  },
  {
    "file": "lowres/rbr/29fraum-another level.png",
    "game": "rbr",
    "name": "29fraum Another Level",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#1e1b28"
  },
  {
    "file": "lowres/rbr/3d versus 2.png",
    "game": "rbr",
    "name": "3d Versus 2",
    "color": "blue",
    "colors": [
      "blue",
      "green",
      "white"
    ],
    "hex": "#1283b4"
  },
  {
    "file": "lowres/rbr/3d versus 3.png",
    "game": "rbr",
    "name": "3d Versus 3",
    "color": "blue",
    "colors": [
      "blue",
      "brown",
      "white"
    ],
    "hex": "#0259ca"
  },
  {
    "file": "lowres/rbr/3d versus.png",
    "game": "rbr",
    "name": "3d Versus",
    "color": "green",
    "colors": [
      "green",
      "blue",
      "white"
    ],
    "hex": "#08eb80"
  },
  {
    "file": "lowres/rbr/60 crates vs 2.png",
    "game": "rbr",
    "name": "60 Crates Vs 2",
    "color": "orange",
    "colors": [
      "orange",
      "gray",
      "brown"
    ],
    "hex": "#e7911d"
  },
  {
    "file": "lowres/rbr/[Chaos] Blaster-Different Types of Players.png",
    "game": "rbr",
    "name": "[chaos] Blaster Different Types Of Players",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "red"
    ],
    "hex": "#0576a4"
  },
  {
    "file": "lowres/rbr/Abishan-End of Season 39 (2).png",
    "game": "rbr",
    "name": "Abishan End Of Season 39 (2)",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#323434"
  },
  {
    "file": "lowres/rbr/Abishan-End of Season 39.png",
    "game": "rbr",
    "name": "Abishan End Of Season 39",
    "color": "white",
    "colors": [
      "white",
      "green",
      "black"
    ],
    "hex": "#fcfafc"
  },
  {
    "file": "lowres/rbr/Abishan-Fluxwave (1).png",
    "game": "rbr",
    "name": "Abishan Fluxwave (1)",
    "color": "purple",
    "colors": [
      "purple",
      "white",
      "brown"
    ],
    "hex": "#6d35dd"
  },
  {
    "file": "lowres/rbr/Abishan-Fluxwave.png",
    "game": "rbr",
    "name": "Abishan Fluxwave",
    "color": "purple",
    "colors": [
      "purple",
      "blue",
      "brown"
    ],
    "hex": "#6932d7"
  },
  {
    "file": "lowres/rbr/Abishan-His rant thumbnail like usual.png",
    "game": "rbr",
    "name": "Abishan His Rant Thumbnail Like Usual",
    "color": "white",
    "colors": [
      "white",
      "red",
      "gray"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/Abishan-Orbitbruh with no shield.png",
    "game": "rbr",
    "name": "Abishan Orbitbruh With No Shield",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "brown"
    ],
    "hex": "#25a4ed"
  },
  {
    "file": "lowres/rbr/Abishan-Peekabo.png",
    "game": "rbr",
    "name": "Abishan Peekabo",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "green"
    ],
    "hex": "#8d512b"
  },
  {
    "file": "lowres/rbr/Abishan-Teeth.png",
    "game": "rbr",
    "name": "Abishan Teeth",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "red"
    ],
    "hex": "#3c3054"
  },
  {
    "file": "lowres/rbr/Abishan-Tetris.png",
    "game": "rbr",
    "name": "Abishan Tetris",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "pink"
    ],
    "hex": "#98d7ee"
  },
  {
    "file": "lowres/rbr/Addict.png",
    "game": "rbr",
    "name": "Addict",
    "color": "white",
    "colors": [
      "white",
      "gray"
    ],
    "hex": "#b7c3d7"
  },
  {
    "file": "lowres/rbr/ArtContestThumbnail.png",
    "game": "rbr",
    "name": "Artcontestthumbnail",
    "color": "black",
    "colors": [
      "black",
      "green",
      "gray"
    ],
    "hex": "#0b4c26"
  },
  {
    "file": "lowres/rbr/aura black fade dim light black tank.png",
    "game": "rbr",
    "name": "Aura Black Fade Dim Light Black Tank",
    "color": "black",
    "colors": [
      "black",
      "gray",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/aura black fade dim light black tank2.png",
    "game": "rbr",
    "name": "Aura Black Fade Dim Light Black Tank2",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "gray"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/basic crate grey.png",
    "game": "rbr",
    "name": "Basic Crate Grey",
    "color": "gray",
    "colors": [
      "gray",
      "white",
      "brown"
    ],
    "hex": "#727170"
  },
  {
    "file": "lowres/rbr/basic red glow tank.png",
    "game": "rbr",
    "name": "Basic Red Glow Tank",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/Bear-Happy Montage.png",
    "game": "rbr",
    "name": "Bear Happy Montage",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#0082b5"
  },
  {
    "file": "lowres/rbr/beautiful blue.png",
    "game": "rbr",
    "name": "Beautiful Blue",
    "color": "blue",
    "colors": [
      "blue",
      "gray",
      "white"
    ],
    "hex": "#3bb9f7"
  },
  {
    "file": "lowres/rbr/believe montage.png",
    "game": "rbr",
    "name": "Believe Montage",
    "color": "white",
    "colors": [
      "white",
      "brown",
      "gray"
    ],
    "hex": "#fef5e1"
  },
  {
    "file": "lowres/rbr/best season revealed blue shocked tank lmao.png",
    "game": "rbr",
    "name": "Best Season Revealed Blue Shocked Tank Lmao",
    "color": "blue",
    "colors": [
      "blue",
      "white"
    ],
    "hex": "#2163c2"
  },
  {
    "file": "lowres/rbr/beta king wood crown brown tank.png",
    "game": "rbr",
    "name": "Beta King Wood Crown Brown Tank",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/BiggestLegends.png",
    "game": "rbr",
    "name": "Biggestlegends",
    "color": "white",
    "colors": [
      "white",
      "red",
      "orange"
    ],
    "hex": "#fefbf8"
  },
  {
    "file": "lowres/rbr/black tank glowing.png",
    "game": "rbr",
    "name": "Black Tank Glowing",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/black tanks versus.png",
    "game": "rbr",
    "name": "Black Tanks Versus",
    "color": "white",
    "colors": [
      "white",
      "black",
      "teal"
    ],
    "hex": "#7dd6f4"
  },
  {
    "file": "lowres/rbr/BladeMontage.png",
    "game": "rbr",
    "name": "Blademontage",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "gray"
    ],
    "hex": "#165ab7"
  },
  {
    "file": "lowres/rbr/blue aura tank.png",
    "game": "rbr",
    "name": "Blue Aura Tank",
    "color": "black",
    "colors": [
      "black",
      "blue"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/blue final montage.png",
    "game": "rbr",
    "name": "Blue Final Montage",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "gray"
    ],
    "hex": "#2bb8f9"
  },
  {
    "file": "lowres/rbr/blue king tank.png",
    "game": "rbr",
    "name": "Blue King Tank",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#397aff"
  },
  {
    "file": "lowres/rbr/blue pixel.png",
    "game": "rbr",
    "name": "Blue Pixel",
    "color": "blue",
    "colors": [
      "blue",
      "white"
    ],
    "hex": "#1f6db6"
  },
  {
    "file": "lowres/rbr/blue tank glowing.png",
    "game": "rbr",
    "name": "Blue Tank Glowing",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "gray"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/blue tank.png",
    "game": "rbr",
    "name": "Blue Tank",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "gray"
    ],
    "hex": "#397aff"
  },
  {
    "file": "lowres/rbr/blue tech glow aura tank.png",
    "game": "rbr",
    "name": "Blue Tech Glow Aura Tank",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#1c6dcb"
  },
  {
    "file": "lowres/rbr/blueaura.png",
    "game": "rbr",
    "name": "Blueaura",
    "color": "blue",
    "colors": [
      "blue",
      "white"
    ],
    "hex": "#1d6dcb"
  },
  {
    "file": "lowres/rbr/blueglass.png",
    "game": "rbr",
    "name": "Blueglass",
    "color": "gray",
    "colors": [
      "gray",
      "white"
    ],
    "hex": "#73aeb9"
  },
  {
    "file": "lowres/rbr/bluemontage.png",
    "game": "rbr",
    "name": "Bluemontage",
    "color": "black",
    "colors": [
      "black",
      "white",
      "blue"
    ],
    "hex": "#2c165b"
  },
  {
    "file": "lowres/rbr/blueportalaura.png",
    "game": "rbr",
    "name": "Blueportalaura",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "teal"
    ],
    "hex": "#0d4b51"
  },
  {
    "file": "lowres/rbr/boatswimmingongems.png",
    "game": "rbr",
    "name": "Boatswimmingongems",
    "color": "green",
    "colors": [
      "green",
      "black",
      "brown"
    ],
    "hex": "#009938"
  },
  {
    "file": "lowres/rbr/BOB1234 gold ghost bat montage.png",
    "game": "rbr",
    "name": "Bob1234 Gold Ghost Bat Montage",
    "color": "black",
    "colors": [
      "black",
      "orange",
      "brown"
    ],
    "hex": "#2e271f"
  },
  {
    "file": "lowres/rbr/BOB1234 yellow ghost bat aura.png",
    "game": "rbr",
    "name": "Bob1234 Yellow Ghost Bat Aura",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "black"
    ],
    "hex": "#91751e"
  },
  {
    "file": "lowres/rbr/Boy With Luv-MAG.png",
    "game": "rbr",
    "name": "Boy With Luv Mag",
    "color": "white",
    "colors": [
      "white",
      "brown"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/brainrot 3 am bullshit.png",
    "game": "rbr",
    "name": "Brainrot 3 Am Bullshit",
    "color": "white",
    "colors": [
      "white",
      "teal",
      "pink"
    ],
    "hex": "#fff9f8"
  },
  {
    "file": "lowres/rbr/burn the house down.png",
    "game": "rbr",
    "name": "Burn The House Down",
    "color": "pink",
    "colors": [
      "pink",
      "black",
      "white"
    ],
    "hex": "#cd9367"
  },
  {
    "file": "lowres/rbr/canon v5 - master of puppets.png",
    "game": "rbr",
    "name": "Canon V5 Master Of Puppets",
    "color": "black",
    "colors": [
      "black",
      "red",
      "brown"
    ],
    "hex": "#37230f"
  },
  {
    "file": "lowres/rbr/Canonv2-Montage.png",
    "game": "rbr",
    "name": "Canonv2 Montage",
    "color": "black",
    "colors": [
      "black",
      "purple",
      "white"
    ],
    "hex": "#3a215e"
  },
  {
    "file": "lowres/rbr/centuries montage.png",
    "game": "rbr",
    "name": "Centuries Montage",
    "color": "orange",
    "colors": [
      "orange",
      "blue",
      "white"
    ],
    "hex": "#e09412"
  },
  {
    "file": "lowres/rbr/chaos montage old.png",
    "game": "rbr",
    "name": "Chaos Montage Old",
    "color": "white",
    "colors": [
      "white",
      "brown",
      "gray"
    ],
    "hex": "#fcfcfc"
  },
  {
    "file": "lowres/rbr/Chaos Montage.png",
    "game": "rbr",
    "name": "Chaos Montage",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "gray"
    ],
    "hex": "#4f4f4f"
  },
  {
    "file": "lowres/rbr/Chaostage.png",
    "game": "rbr",
    "name": "Chaostage",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "black"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/Controllerprogression.png",
    "game": "rbr",
    "name": "Controllerprogression",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "white"
    ],
    "hex": "#002b5b"
  },
  {
    "file": "lowres/rbr/conversations montage.png",
    "game": "rbr",
    "name": "Conversations Montage",
    "color": "white",
    "colors": [
      "white",
      "blue"
    ],
    "hex": "#fafdfd"
  },
  {
    "file": "lowres/rbr/CoolGoldThumbnail.png",
    "game": "rbr",
    "name": "Coolgoldthumbnail",
    "color": "black",
    "colors": [
      "black",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/crate opener tool.png",
    "game": "rbr",
    "name": "Crate Opener Tool",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#1098dc"
  },
  {
    "file": "lowres/rbr/crates.png",
    "game": "rbr",
    "name": "Crates",
    "color": "white",
    "colors": [
      "white",
      "yellow",
      "brown"
    ],
    "hex": "#cac1b9"
  },
  {
    "file": "lowres/rbr/cratestanks.png",
    "game": "rbr",
    "name": "Cratestanks",
    "color": "black",
    "colors": [
      "black",
      "gray",
      "white"
    ],
    "hex": "#093d73"
  },
  {
    "file": "lowres/rbr/crown on blue background.png",
    "game": "rbr",
    "name": "Crown On Blue Background",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "orange"
    ],
    "hex": "#397aff"
  },
  {
    "file": "lowres/rbr/cursed rbr merch (don't exist).png",
    "game": "rbr",
    "name": "Cursed Rbr Merch (don't Exist)",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "brown"
    ],
    "hex": "#2ba4e5"
  },
  {
    "file": "lowres/rbr/cyan aura around tank.png",
    "game": "rbr",
    "name": "Cyan Aura Around Tank",
    "color": "teal",
    "colors": [
      "teal",
      "black",
      "gray"
    ],
    "hex": "#06b69e"
  },
  {
    "file": "lowres/rbr/cyan aura tank.png",
    "game": "rbr",
    "name": "Cyan Aura Tank",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "teal"
    ],
    "hex": "#0e4c53"
  },
  {
    "file": "lowres/rbr/cyan red aura.png",
    "game": "rbr",
    "name": "Cyan Red Aura",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "gray"
    ],
    "hex": "#641011"
  },
  {
    "file": "lowres/rbr/Dancing in the dark black tank montage.png",
    "game": "rbr",
    "name": "Dancing In The Dark Black Tank Montage",
    "color": "black",
    "colors": [
      "black",
      "white",
      "gray"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/Decals montage.png",
    "game": "rbr",
    "name": "Decals Montage",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "purple"
    ],
    "hex": "#3465b2"
  },
  {
    "file": "lowres/rbr/deepfried_mogging.jpg",
    "game": "rbr",
    "name": "Deepfried Mogging",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#1c1c1c"
  },
  {
    "file": "lowres/rbr/discord montage.png",
    "game": "rbr",
    "name": "Discord Montage",
    "color": "black",
    "colors": [
      "black",
      "white",
      "gray"
    ],
    "hex": "#060507"
  },
  {
    "file": "lowres/rbr/DreptageMontageV1.png",
    "game": "rbr",
    "name": "Dreptagemontagev1",
    "color": "brown",
    "colors": [
      "brown",
      "gray",
      "black"
    ],
    "hex": "#603e0f"
  },
  {
    "file": "lowres/rbr/DreptageMontageV2.png",
    "game": "rbr",
    "name": "Dreptagemontagev2",
    "color": "brown",
    "colors": [
      "brown",
      "gray",
      "black"
    ],
    "hex": "#5d3c0d"
  },
  {
    "file": "lowres/rbr/DreptageMontageV3.png",
    "game": "rbr",
    "name": "Dreptagemontagev3",
    "color": "white",
    "colors": [
      "white",
      "black",
      "brown"
    ],
    "hex": "#fdfbf6"
  },
  {
    "file": "lowres/rbr/DreptageMontageV4.png",
    "game": "rbr",
    "name": "Dreptagemontagev4",
    "color": "black",
    "colors": [
      "black",
      "white",
      "gray"
    ],
    "hex": "#01121b"
  },
  {
    "file": "lowres/rbr/DreptageMontageV5.png",
    "game": "rbr",
    "name": "Dreptagemontagev5",
    "color": "black",
    "colors": [
      "black",
      "white",
      "blue"
    ],
    "hex": "#01131c"
  },
  {
    "file": "lowres/rbr/DreptageMontageV7.png",
    "game": "rbr",
    "name": "Dreptagemontagev7",
    "color": "white",
    "colors": [
      "white",
      "black",
      "gray"
    ],
    "hex": "#fafaf9"
  },
  {
    "file": "lowres/rbr/Edit1.png",
    "game": "rbr",
    "name": "Edit1",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#161e1a"
  },
  {
    "file": "lowres/rbr/Elite crates RBR.png",
    "game": "rbr",
    "name": "Elite Crates Rbr",
    "color": "orange",
    "colors": [
      "orange",
      "yellow",
      "black"
    ],
    "hex": "#cd7303"
  },
  {
    "file": "lowres/rbr/Elite-TinyTurtleTots.png",
    "game": "rbr",
    "name": "Elite Tinyturtletots",
    "color": "yellow",
    "colors": [
      "yellow",
      "orange",
      "black"
    ],
    "hex": "#feaa0c"
  },
  {
    "file": "lowres/rbr/ERROR.png",
    "game": "rbr",
    "name": "Error",
    "color": "black",
    "colors": [
      "black",
      "red",
      "gray"
    ],
    "hex": "#393837"
  },
  {
    "file": "lowres/rbr/escape1.png",
    "game": "rbr",
    "name": "Escape1",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/escape2.png",
    "game": "rbr",
    "name": "Escape2",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/escape3.png",
    "game": "rbr",
    "name": "Escape3",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/escape4.png",
    "game": "rbr",
    "name": "Escape4",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/Everblaze-Electrodynamix.png",
    "game": "rbr",
    "name": "Everblaze Electrodynamix",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "white"
    ],
    "hex": "#761916"
  },
  {
    "file": "lowres/rbr/Fighter 2 blue blade aura.png",
    "game": "rbr",
    "name": "Fighter 2 Blue Blade Aura",
    "color": "white",
    "colors": [
      "white",
      "black",
      "gray"
    ],
    "hex": "#e0f0f4"
  },
  {
    "file": "lowres/rbr/Final Montage (2).png",
    "game": "rbr",
    "name": "Final Montage (2)",
    "color": "white",
    "colors": [
      "white",
      "blue"
    ],
    "hex": "#fcfefe"
  },
  {
    "file": "lowres/rbr/Final Montage (3).png",
    "game": "rbr",
    "name": "Final Montage (3)",
    "color": "white",
    "colors": [
      "white",
      "blue"
    ],
    "hex": "#fcfefe"
  },
  {
    "file": "lowres/rbr/final montage purple tread.png",
    "game": "rbr",
    "name": "Final Montage Purple Tread",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "gray"
    ],
    "hex": "#fafdfd"
  },
  {
    "file": "lowres/rbr/Final Montage.png",
    "game": "rbr",
    "name": "Final Montage",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#005ca7"
  },
  {
    "file": "lowres/rbr/first place crown.png",
    "game": "rbr",
    "name": "First Place Crown",
    "color": "orange",
    "colors": [
      "orange",
      "yellow",
      "black"
    ],
    "hex": "#ef8a03"
  },
  {
    "file": "lowres/rbr/First Video.png",
    "game": "rbr",
    "name": "First Video",
    "color": "orange",
    "colors": [
      "orange",
      "white",
      "red"
    ],
    "hex": "#ff794d"
  },
  {
    "file": "lowres/rbr/FirstPlaceMontage.png",
    "game": "rbr",
    "name": "Firstplacemontage",
    "color": "red",
    "colors": [
      "red",
      "white",
      "orange"
    ],
    "hex": "#bd591c"
  },
  {
    "file": "lowres/rbr/FlakMeta.png",
    "game": "rbr",
    "name": "Flakmeta",
    "color": "yellow",
    "colors": [
      "yellow",
      "black",
      "white"
    ],
    "hex": "#ffd815"
  },
  {
    "file": "lowres/rbr/glassbubble.png",
    "game": "rbr",
    "name": "Glassbubble",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "black"
    ],
    "hex": "#474357"
  },
  {
    "file": "lowres/rbr/glow on blue tank.png",
    "game": "rbr",
    "name": "Glow On Blue Tank",
    "color": "black",
    "colors": [
      "black",
      "gray"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/glow on cyan tank.png",
    "game": "rbr",
    "name": "Glow On Cyan Tank",
    "color": "black",
    "colors": [
      "black",
      "teal",
      "blue"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/glow on red tank.png",
    "game": "rbr",
    "name": "Glow On Red Tank",
    "color": "black",
    "colors": [
      "black",
      "pink",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/glow on yellow tank.png",
    "game": "rbr",
    "name": "Glow On Yellow Tank",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/gold aura tank (2).png",
    "game": "rbr",
    "name": "Gold Aura Tank (2)",
    "color": "black",
    "colors": [
      "black",
      "orange",
      "yellow"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/gold aura tank montage 2.png",
    "game": "rbr",
    "name": "Gold Aura Tank Montage 2",
    "color": "brown",
    "colors": [
      "brown",
      "orange",
      "black"
    ],
    "hex": "#83521c"
  },
  {
    "file": "lowres/rbr/gold aura tank montage.png",
    "game": "rbr",
    "name": "Gold Aura Tank Montage",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#1f1507"
  },
  {
    "file": "lowres/rbr/gold aura tank.png",
    "game": "rbr",
    "name": "Gold Aura Tank",
    "color": "black",
    "colors": [
      "black",
      "orange",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/gold aura.png",
    "game": "rbr",
    "name": "Gold Aura",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "orange"
    ],
    "hex": "#5b3f0a"
  },
  {
    "file": "lowres/rbr/gold leader.png",
    "game": "rbr",
    "name": "Gold Leader",
    "color": "red",
    "colors": [
      "red",
      "white",
      "orange"
    ],
    "hex": "#bd511b"
  },
  {
    "file": "lowres/rbr/gold light on gold tank.png",
    "game": "rbr",
    "name": "Gold Light On Gold Tank",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "orange"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/gold radiant aura tank god.png",
    "game": "rbr",
    "name": "Gold Radiant Aura Tank God",
    "color": "white",
    "colors": [
      "white",
      "gray",
      "brown"
    ],
    "hex": "#decba1"
  },
  {
    "file": "lowres/rbr/gold trail aura tank.png",
    "game": "rbr",
    "name": "Gold Trail Aura Tank",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#39290c"
  },
  {
    "file": "lowres/rbr/gold trail gold tank.png",
    "game": "rbr",
    "name": "Gold Trail Gold Tank",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "orange"
    ],
    "hex": "#452f09"
  },
  {
    "file": "lowres/rbr/gold twitch.png",
    "game": "rbr",
    "name": "Gold Twitch",
    "color": "brown",
    "colors": [
      "brown",
      "orange"
    ],
    "hex": "#813811"
  },
  {
    "file": "lowres/rbr/gold youtube.png",
    "game": "rbr",
    "name": "Gold Youtube",
    "color": "brown",
    "colors": [
      "brown",
      "orange",
      "yellow"
    ],
    "hex": "#863d12"
  },
  {
    "file": "lowres/rbr/goldauramontage.png",
    "game": "rbr",
    "name": "Goldauramontage",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#1f1506"
  },
  {
    "file": "lowres/rbr/GoldCrownedTank.png",
    "game": "rbr",
    "name": "Goldcrownedtank",
    "color": "yellow",
    "colors": [
      "yellow",
      "white",
      "black"
    ],
    "hex": "#ffbf28"
  },
  {
    "file": "lowres/rbr/goldwave.png",
    "game": "rbr",
    "name": "Goldwave",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "orange"
    ],
    "hex": "#452f0a"
  },
  {
    "file": "lowres/rbr/green gems.png",
    "game": "rbr",
    "name": "Green Gems",
    "color": "green",
    "colors": [
      "green",
      "black"
    ],
    "hex": "#03bd43"
  },
  {
    "file": "lowres/rbr/green helicopter.png",
    "game": "rbr",
    "name": "Green Helicopter",
    "color": "white",
    "colors": [
      "white",
      "green",
      "black"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/grinding ranked.png",
    "game": "rbr",
    "name": "Grinding Ranked",
    "color": "brown",
    "colors": [
      "brown",
      "orange",
      "yellow"
    ],
    "hex": "#763916"
  },
  {
    "file": "lowres/rbr/Grinding.png",
    "game": "rbr",
    "name": "Grinding",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "white"
    ],
    "hex": "#022246"
  },
  {
    "file": "lowres/rbr/Hamburger.png",
    "game": "rbr",
    "name": "Hamburger",
    "color": "orange",
    "colors": [
      "orange",
      "white",
      "brown"
    ],
    "hex": "#d76e0a"
  },
  {
    "file": "lowres/rbr/heartless montage.png",
    "game": "rbr",
    "name": "Heartless Montage",
    "color": "red",
    "colors": [
      "red",
      "white",
      "black"
    ],
    "hex": "#cf1b1b"
  },
  {
    "file": "lowres/rbr/How Pros DO IT remastered Thumbnail.png",
    "game": "rbr",
    "name": "How Pros Do It Remastered Thumbnail",
    "color": "white",
    "colors": [
      "white",
      "yellow",
      "black"
    ],
    "hex": "#fcfcd9"
  },
  {
    "file": "lowres/rbr/How to design thumbnail.png",
    "game": "rbr",
    "name": "How To Design Thumbnail",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "white"
    ],
    "hex": "#003975"
  },
  {
    "file": "lowres/rbr/How to get slayer badges.png",
    "game": "rbr",
    "name": "How To Get Slayer Badges",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "white"
    ],
    "hex": "#03090b"
  },
  {
    "file": "lowres/rbr/HowProsDoIt(old).png",
    "game": "rbr",
    "name": "Howprosdoit(old)",
    "color": "white",
    "colors": [
      "white",
      "orange",
      "brown"
    ],
    "hex": "#fafaf0"
  },
  {
    "file": "lowres/rbr/HowProsDoIT.png",
    "game": "rbr",
    "name": "Howprosdoit",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "black"
    ],
    "hex": "#fcfcf1"
  },
  {
    "file": "lowres/rbr/HuyRey-Community Montage.png",
    "game": "rbr",
    "name": "Huyrey Community Montage",
    "color": "white",
    "colors": [
      "white",
      "purple",
      "yellow"
    ],
    "hex": "#feffff"
  },
  {
    "file": "lowres/rbr/Huyrey-Im Back!.png",
    "game": "rbr",
    "name": "Huyrey Im Back!",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#047097"
  },
  {
    "file": "lowres/rbr/In The Sky.png",
    "game": "rbr",
    "name": "In The Sky",
    "color": "white",
    "colors": [
      "white",
      "black",
      "blue"
    ],
    "hex": "#e0eaf2"
  },
  {
    "file": "lowres/rbr/Islands.png",
    "game": "rbr",
    "name": "Islands",
    "color": "black",
    "colors": [
      "black",
      "teal",
      "white"
    ],
    "hex": "#023e5c"
  },
  {
    "file": "lowres/rbr/JDAMontageThumbnail.png",
    "game": "rbr",
    "name": "Jdamontagethumbnail",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "gray"
    ],
    "hex": "#10213a"
  },
  {
    "file": "lowres/rbr/jimwah-metamorphosis.png",
    "game": "rbr",
    "name": "Jimwah Metamorphosis",
    "color": "purple",
    "colors": [
      "purple",
      "white",
      "black"
    ],
    "hex": "#525091"
  },
  {
    "file": "lowres/rbr/kills montage black tank.png",
    "game": "rbr",
    "name": "Kills Montage Black Tank",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/KingRBR-montage.png",
    "game": "rbr",
    "name": "Kingrbr Montage",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#004ec9"
  },
  {
    "file": "lowres/rbr/larger tank beautiful tank.png",
    "game": "rbr",
    "name": "Larger Tank Beautiful Tank",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#74d6ec"
  },
  {
    "file": "lowres/rbr/legend-believer.png",
    "game": "rbr",
    "name": "Legend Believer",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#126991"
  },
  {
    "file": "lowres/rbr/Let Go blue blade montage.png",
    "game": "rbr",
    "name": "Let Go Blue Blade Montage",
    "color": "orange",
    "colors": [
      "orange",
      "blue",
      "teal"
    ],
    "hex": "#e58513"
  },
  {
    "file": "lowres/rbr/level 50 gold tank.png",
    "game": "rbr",
    "name": "Level 50 Gold Tank",
    "color": "blue",
    "colors": [
      "blue",
      "orange",
      "black"
    ],
    "hex": "#397aff"
  },
  {
    "file": "lowres/rbr/level 50.png",
    "game": "rbr",
    "name": "Level 50",
    "color": "red",
    "colors": [
      "red",
      "orange",
      "brown"
    ],
    "hex": "#b24b02"
  },
  {
    "file": "lowres/rbr/Light-communitymontage.png",
    "game": "rbr",
    "name": "Light Communitymontage",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "gray"
    ],
    "hex": "#fcfdfd"
  },
  {
    "file": "lowres/rbr/light3.png",
    "game": "rbr",
    "name": "Light3",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/Lightalt-3 Vets.png",
    "game": "rbr",
    "name": "Lightalt 3 Vets",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "green"
    ],
    "hex": "#055c2b"
  },
  {
    "file": "lowres/rbr/lucasorbr-TIMELESS.png",
    "game": "rbr",
    "name": "Lucasorbr Timeless",
    "color": "white",
    "colors": [
      "white",
      "gray",
      "black"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/Lucid Dreams 2 blue blade aura.png",
    "game": "rbr",
    "name": "Lucid Dreams 2 Blue Blade Aura",
    "color": "white",
    "colors": [
      "white",
      "black",
      "blue"
    ],
    "hex": "#e0f2f7"
  },
  {
    "file": "lowres/rbr/MAG- One Call.png",
    "game": "rbr",
    "name": "Mag One Call",
    "color": "black",
    "colors": [
      "black",
      "gray",
      "white"
    ],
    "hex": "#2b2d2d"
  },
  {
    "file": "lowres/rbr/MAG-Capo.png",
    "game": "rbr",
    "name": "Mag Capo",
    "color": "brown",
    "colors": [
      "brown",
      "orange",
      "black"
    ],
    "hex": "#8b611f"
  },
  {
    "file": "lowres/rbr/MAG-Dark Thoughts.png",
    "game": "rbr",
    "name": "Mag Dark Thoughts",
    "color": "purple",
    "colors": [
      "purple",
      "white",
      "brown"
    ],
    "hex": "#4f3d92"
  },
  {
    "file": "lowres/rbr/MAG-End of Season 38.png",
    "game": "rbr",
    "name": "Mag End Of Season 38",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#108dcb"
  },
  {
    "file": "lowres/rbr/MAG-End of Season 41.png",
    "game": "rbr",
    "name": "Mag End Of Season 41",
    "color": "orange",
    "colors": [
      "orange",
      "white",
      "black"
    ],
    "hex": "#b18336"
  },
  {
    "file": "lowres/rbr/MAG-End of Season 44.png",
    "game": "rbr",
    "name": "Mag End Of Season 44",
    "color": "white",
    "colors": [
      "white",
      "brown",
      "black"
    ],
    "hex": "#fefffe"
  },
  {
    "file": "lowres/rbr/Mag-OneCall.png",
    "game": "rbr",
    "name": "Mag Onecall",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "gray"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/MagYTR End of Season 37.png",
    "game": "rbr",
    "name": "Magytr End Of Season 37",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#08a0d3"
  },
  {
    "file": "lowres/rbr/MagYTR-LotOfMe.png",
    "game": "rbr",
    "name": "Magytr Lotofme",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#7cc2e4"
  },
  {
    "file": "lowres/rbr/MakeCoolThumbnails.png",
    "game": "rbr",
    "name": "Makecoolthumbnails",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#004895"
  },
  {
    "file": "lowres/rbr/Manhunt 1v3.png",
    "game": "rbr",
    "name": "Manhunt 1v3",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "green"
    ],
    "hex": "#005ab6"
  },
  {
    "file": "lowres/rbr/MasteringDrill.png",
    "game": "rbr",
    "name": "Masteringdrill",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "gray"
    ],
    "hex": "#0e1746"
  },
  {
    "file": "lowres/rbr/MasteringFlak.png",
    "game": "rbr",
    "name": "Masteringflak",
    "color": "yellow",
    "colors": [
      "yellow",
      "orange",
      "brown"
    ],
    "hex": "#ffd72c"
  },
  {
    "file": "lowres/rbr/MasteringGrenade.png",
    "game": "rbr",
    "name": "Masteringgrenade",
    "color": "red",
    "colors": [
      "red",
      "black",
      "brown"
    ],
    "hex": "#fd0000"
  },
  {
    "file": "lowres/rbr/MasteringHoming.png",
    "game": "rbr",
    "name": "Masteringhoming",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#4b9af3"
  },
  {
    "file": "lowres/rbr/MasteringJetpack.png",
    "game": "rbr",
    "name": "Masteringjetpack",
    "color": "red",
    "colors": [
      "red",
      "black",
      "brown"
    ],
    "hex": "#fd0000"
  },
  {
    "file": "lowres/rbr/MasteringLaser.png",
    "game": "rbr",
    "name": "Masteringlaser",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#4c9af1"
  },
  {
    "file": "lowres/rbr/MasteringMine.png",
    "game": "rbr",
    "name": "Masteringmine",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "red"
    ],
    "hex": "#8a2632"
  },
  {
    "file": "lowres/rbr/MasteringNuke.png",
    "game": "rbr",
    "name": "Masteringnuke",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "gray"
    ],
    "hex": "#4295f7"
  },
  {
    "file": "lowres/rbr/MasteringPoison.png",
    "game": "rbr",
    "name": "Masteringpoison",
    "color": "gray",
    "colors": [
      "gray",
      "green",
      "brown"
    ],
    "hex": "#79895e"
  },
  {
    "file": "lowres/rbr/MasteringRapid.png",
    "game": "rbr",
    "name": "Masteringrapid",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#4a9cf6"
  },
  {
    "file": "lowres/rbr/MasteringShield.png",
    "game": "rbr",
    "name": "Masteringshield",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#509ef3"
  },
  {
    "file": "lowres/rbr/meme.png",
    "game": "rbr",
    "name": "Meme",
    "color": "teal",
    "colors": [
      "teal",
      "blue",
      "gray"
    ],
    "hex": "#007891"
  },
  {
    "file": "lowres/rbr/moon chaos montage.png",
    "game": "rbr",
    "name": "Moon Chaos Montage",
    "color": "gray",
    "colors": [
      "gray",
      "white",
      "brown"
    ],
    "hex": "#69787f"
  },
  {
    "file": "lowres/rbr/mr.lucasorbr-Hope.png",
    "game": "rbr",
    "name": "Mr.lucasorbr Hope",
    "color": "brown",
    "colors": [
      "brown",
      "orange",
      "white"
    ],
    "hex": "#6d481f"
  },
  {
    "file": "lowres/rbr/MusicalMontage.png",
    "game": "rbr",
    "name": "Musicalmontage",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#262a31"
  },
  {
    "file": "lowres/rbr/My ordinary Life.png",
    "game": "rbr",
    "name": "My Ordinary Life",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "green"
    ],
    "hex": "#3f280f"
  },
  {
    "file": "lowres/rbr/Mythic-Dandelions.png",
    "game": "rbr",
    "name": "Mythic Dandelions",
    "color": "orange",
    "colors": [
      "orange",
      "white",
      "brown"
    ],
    "hex": "#e39819"
  },
  {
    "file": "lowres/rbr/natedrbr-montage.png",
    "game": "rbr",
    "name": "Natedrbr Montage",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#3e160a"
  },
  {
    "file": "lowres/rbr/Naturals.png",
    "game": "rbr",
    "name": "Naturals",
    "color": "purple",
    "colors": [
      "purple",
      "black",
      "red"
    ],
    "hex": "#512081"
  },
  {
    "file": "lowres/rbr/Nebula-number1player.png",
    "game": "rbr",
    "name": "Nebula Number1player",
    "color": "black",
    "colors": [
      "black",
      "white",
      "gray"
    ],
    "hex": "#362729"
  },
  {
    "file": "lowres/rbr/Nebulage.png",
    "game": "rbr",
    "name": "Nebulage",
    "color": "green",
    "colors": [
      "green",
      "white",
      "black"
    ],
    "hex": "#026f47"
  },
  {
    "file": "lowres/rbr/NebulaMashup.png",
    "game": "rbr",
    "name": "Nebulamashup",
    "color": "orange",
    "colors": [
      "orange",
      "brown",
      "black"
    ],
    "hex": "#df813f"
  },
  {
    "file": "lowres/rbr/NebulaMashupFinal.png",
    "game": "rbr",
    "name": "Nebulamashupfinal",
    "color": "orange",
    "colors": [
      "orange",
      "black",
      "brown"
    ],
    "hex": "#e08442"
  },
  {
    "file": "lowres/rbr/New update.png",
    "game": "rbr",
    "name": "New Update",
    "color": "blue",
    "colors": [
      "blue",
      "teal",
      "white"
    ],
    "hex": "#27c1c0"
  },
  {
    "file": "lowres/rbr/newmemes.png",
    "game": "rbr",
    "name": "Newmemes",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#004aad"
  },
  {
    "file": "lowres/rbr/NewSeason.png",
    "game": "rbr",
    "name": "Newseason",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "red"
    ],
    "hex": "#519ece"
  },
  {
    "file": "lowres/rbr/NewSportsSeason.png",
    "game": "rbr",
    "name": "Newsportsseason",
    "color": "black",
    "colors": [
      "black",
      "white",
      "blue"
    ],
    "hex": "#1b1623"
  },
  {
    "file": "lowres/rbr/nice background.png",
    "game": "rbr",
    "name": "Nice Background",
    "color": "blue",
    "colors": [
      "blue",
      "teal",
      "green"
    ],
    "hex": "#046ec0"
  },
  {
    "file": "lowres/rbr/NoEscape.png",
    "game": "rbr",
    "name": "Noescape",
    "color": "black",
    "colors": [
      "black",
      "brown"
    ],
    "hex": "#0e0f0e"
  },
  {
    "file": "lowres/rbr/NoobToPro.png",
    "game": "rbr",
    "name": "Noobtopro",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "white"
    ],
    "hex": "#3a3837"
  },
  {
    "file": "lowres/rbr/nostalgialight.png",
    "game": "rbr",
    "name": "Nostalgialight",
    "color": "black",
    "colors": [
      "black",
      "white",
      "brown"
    ],
    "hex": "#0d0d0d"
  },
  {
    "file": "lowres/rbr/NostalgiaMontage1.png",
    "game": "rbr",
    "name": "Nostalgiamontage1",
    "color": "white",
    "colors": [
      "white",
      "blue"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/NostalgiaMontage2.png",
    "game": "rbr",
    "name": "Nostalgiamontage2",
    "color": "white",
    "colors": [
      "white",
      "red"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/Nuclear RBR-Challenges.png",
    "game": "rbr",
    "name": "Nuclear Rbr Challenges",
    "color": "brown",
    "colors": [
      "brown",
      "blue",
      "black"
    ],
    "hex": "#604531"
  },
  {
    "file": "lowres/rbr/number 1 best player.png",
    "game": "rbr",
    "name": "Number 1 Best Player",
    "color": "white",
    "colors": [
      "white",
      "gray",
      "brown"
    ],
    "hex": "#fafbfb"
  },
  {
    "file": "lowres/rbr/Ohio3amthumbnail.png",
    "game": "rbr",
    "name": "Ohio3amthumbnail",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "teal"
    ],
    "hex": "#007fb3"
  },
  {
    "file": "lowres/rbr/OldSeason36Thumbnail.png",
    "game": "rbr",
    "name": "Oldseason36thumbnail",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "gray"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/one call.png",
    "game": "rbr",
    "name": "One Call",
    "color": "white",
    "colors": [
      "white",
      "black",
      "gray"
    ],
    "hex": "#fefefe"
  },
  {
    "file": "lowres/rbr/opening crates basic crates.png",
    "game": "rbr",
    "name": "Opening Crates Basic Crates",
    "color": "gray",
    "colors": [
      "gray",
      "white",
      "black"
    ],
    "hex": "#7a7978"
  },
  {
    "file": "lowres/rbr/Opening Elite Crates.png",
    "game": "rbr",
    "name": "Opening Elite Crates",
    "color": "orange",
    "colors": [
      "orange",
      "white",
      "black"
    ],
    "hex": "#c76602"
  },
  {
    "file": "lowres/rbr/opening my third elite crate.png",
    "game": "rbr",
    "name": "Opening My Third Elite Crate",
    "color": "white",
    "colors": [
      "white",
      "yellow",
      "orange"
    ],
    "hex": "#cac6c1"
  },
  {
    "file": "lowres/rbr/orange montage.png",
    "game": "rbr",
    "name": "Orange Montage",
    "color": "orange",
    "colors": [
      "orange",
      "white",
      "brown"
    ],
    "hex": "#ff7201"
  },
  {
    "file": "lowres/rbr/orange pumpkin metamorphosis montage.png",
    "game": "rbr",
    "name": "Orange Pumpkin Metamorphosis Montage",
    "color": "black",
    "colors": [
      "black",
      "yellow",
      "orange"
    ],
    "hex": "#3a3018"
  },
  {
    "file": "lowres/rbr/Paranoia.png",
    "game": "rbr",
    "name": "Paranoia",
    "color": "gray",
    "colors": [
      "gray",
      "brown",
      "white"
    ],
    "hex": "#a7a7a7"
  },
  {
    "file": "lowres/rbr/pile of gems.png",
    "game": "rbr",
    "name": "Pile Of Gems",
    "color": "green",
    "colors": [
      "green",
      "black"
    ],
    "hex": "#00c54f"
  },
  {
    "file": "lowres/rbr/pink music video thumbnail.png",
    "game": "rbr",
    "name": "Pink Music Video Thumbnail",
    "color": "black",
    "colors": [
      "black",
      "pink",
      "purple"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/pink tank basic.png",
    "game": "rbr",
    "name": "Pink Tank Basic",
    "color": "white",
    "colors": [
      "white",
      "gray"
    ],
    "hex": "#f7adc4"
  },
  {
    "file": "lowres/rbr/pink wave in bubbles.png",
    "game": "rbr",
    "name": "Pink Wave In Bubbles",
    "color": "black",
    "colors": [
      "black",
      "gray",
      "white"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/pinkglass.png",
    "game": "rbr",
    "name": "Pinkglass",
    "color": "white",
    "colors": [
      "white",
      "gray"
    ],
    "hex": "#f7adc4"
  },
  {
    "file": "lowres/rbr/pixel.png",
    "game": "rbr",
    "name": "Pixel",
    "color": "blue",
    "colors": [
      "blue",
      "white"
    ],
    "hex": "#1f6db6"
  },
  {
    "file": "lowres/rbr/pixels.png",
    "game": "rbr",
    "name": "Pixels",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "black"
    ],
    "hex": "#9be7fe"
  },
  {
    "file": "lowres/rbr/PlayingVRRocketBotRoyale.png",
    "game": "rbr",
    "name": "Playingvrrocketbotroyale",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#4183ea"
  },
  {
    "file": "lowres/rbr/portalbottom1.png",
    "game": "rbr",
    "name": "Portalbottom1",
    "color": "black",
    "colors": [
      "black",
      "gray",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/portalbottom2.png",
    "game": "rbr",
    "name": "Portalbottom2",
    "color": "black",
    "colors": [
      "black",
      "blue"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/pro gameplay funny.png",
    "game": "rbr",
    "name": "Pro Gameplay Funny",
    "color": "teal",
    "colors": [
      "teal",
      "red",
      "blue"
    ],
    "hex": "#00748d"
  },
  {
    "file": "lowres/rbr/Protank123=Baby im back.png",
    "game": "rbr",
    "name": "Protank123=baby Im Back",
    "color": "orange",
    "colors": [
      "orange",
      "white",
      "black"
    ],
    "hex": "#aa7e3e"
  },
  {
    "file": "lowres/rbr/purple aura tank.png",
    "game": "rbr",
    "name": "Purple Aura Tank",
    "color": "black",
    "colors": [
      "black",
      "gray",
      "brown"
    ],
    "hex": "#46021d"
  },
  {
    "file": "lowres/rbr/quad kill x1.png",
    "game": "rbr",
    "name": "Quad Kill X1",
    "color": "gray",
    "colors": [
      "gray",
      "white",
      "black"
    ],
    "hex": "#a8a8a8"
  },
  {
    "file": "lowres/rbr/quad kill x10.png",
    "game": "rbr",
    "name": "Quad Kill X10",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "brown"
    ],
    "hex": "#b9eaf8"
  },
  {
    "file": "lowres/rbr/quad kill x100.png",
    "game": "rbr",
    "name": "Quad Kill X100",
    "color": "purple",
    "colors": [
      "purple",
      "white",
      "black"
    ],
    "hex": "#aa56da"
  },
  {
    "file": "lowres/rbr/quad kill x25.png",
    "game": "rbr",
    "name": "Quad Kill X25",
    "color": "green",
    "colors": [
      "green",
      "black"
    ],
    "hex": "#2cd72c"
  },
  {
    "file": "lowres/rbr/quad kill x50.png",
    "game": "rbr",
    "name": "Quad Kill X50",
    "color": "blue",
    "colors": [
      "blue",
      "black"
    ],
    "hex": "#0e93e2"
  },
  {
    "file": "lowres/rbr/quad kill x500.png",
    "game": "rbr",
    "name": "Quad Kill X500",
    "color": "yellow",
    "colors": [
      "yellow",
      "orange",
      "black"
    ],
    "hex": "#f3a212"
  },
  {
    "file": "lowres/rbr/Rankedchaos.png",
    "game": "rbr",
    "name": "Rankedchaos",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "black"
    ],
    "hex": "#fffefe"
  },
  {
    "file": "lowres/rbr/Ratingmaps.png",
    "game": "rbr",
    "name": "Ratingmaps",
    "color": "white",
    "colors": [
      "white",
      "black",
      "blue"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/RBR tips thumbnail.png",
    "game": "rbr",
    "name": "Rbr Tips Thumbnail",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#2bb4e7"
  },
  {
    "file": "lowres/rbr/RBRGLITCH.png",
    "game": "rbr",
    "name": "Rbrglitch",
    "color": "brown",
    "colors": [
      "brown",
      "gray",
      "black"
    ],
    "hex": "#4f5051"
  },
  {
    "file": "lowres/rbr/RBRGuide.png",
    "game": "rbr",
    "name": "Rbrguide",
    "color": "orange",
    "colors": [
      "orange",
      "yellow",
      "pink"
    ],
    "hex": "#d8a734"
  },
  {
    "file": "lowres/rbr/RBRMontages.png",
    "game": "rbr",
    "name": "Rbrmontages",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "white"
    ],
    "hex": "#4d2d1d"
  },
  {
    "file": "lowres/rbr/red and blue tank.png",
    "game": "rbr",
    "name": "Red And Blue Tank",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "gray"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/red aura.png",
    "game": "rbr",
    "name": "Red Aura",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "white"
    ],
    "hex": "#6b060f"
  },
  {
    "file": "lowres/rbr/red glowing aura tank.png",
    "game": "rbr",
    "name": "Red Glowing Aura Tank",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "pink"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/red glowing portal on tank.png",
    "game": "rbr",
    "name": "Red Glowing Portal On Tank",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "pink"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/RedMontage.png",
    "game": "rbr",
    "name": "Redmontage",
    "color": "white",
    "colors": [
      "white",
      "black",
      "pink"
    ],
    "hex": "#fdf7f2"
  },
  {
    "file": "lowres/rbr/redspotlight.png",
    "game": "rbr",
    "name": "Redspotlight",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "gray"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/RocketBot-Animals (2).png",
    "game": "rbr",
    "name": "Rocketbot Animals (2)",
    "color": "brown",
    "colors": [
      "brown",
      "gray",
      "black"
    ],
    "hex": "#4a494e"
  },
  {
    "file": "lowres/rbr/RocketBot-Animals (3).png",
    "game": "rbr",
    "name": "Rocketbot Animals (3)",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "white"
    ],
    "hex": "#9e7130"
  },
  {
    "file": "lowres/rbr/RocketBot-Animals (4).png",
    "game": "rbr",
    "name": "Rocketbot Animals (4)",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "red"
    ],
    "hex": "#3e3265"
  },
  {
    "file": "lowres/rbr/RooocjetBot- Final Montage.png",
    "game": "rbr",
    "name": "Rooocjetbot Final Montage",
    "color": "gray",
    "colors": [
      "gray",
      "white",
      "black"
    ],
    "hex": "#67777d"
  },
  {
    "file": "lowres/rbr/Rooocketbot-ransom montage.png",
    "game": "rbr",
    "name": "Rooocketbot Ransom Montage",
    "color": "white",
    "colors": [
      "white",
      "black",
      "teal"
    ],
    "hex": "#fdfffe"
  },
  {
    "file": "lowres/rbr/Royalty.png",
    "game": "rbr",
    "name": "Royalty",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "orange"
    ],
    "hex": "#623e07"
  },
  {
    "file": "lowres/rbr/Rush E montage.png",
    "game": "rbr",
    "name": "Rush E Montage",
    "color": "white",
    "colors": [
      "white",
      "black",
      "yellow"
    ],
    "hex": "#f9f8f8"
  },
  {
    "file": "lowres/rbr/Seaofproblems.png",
    "game": "rbr",
    "name": "Seaofproblems",
    "color": "red",
    "colors": [
      "red",
      "gray",
      "brown"
    ],
    "hex": "#e90002"
  },
  {
    "file": "lowres/rbr/Season 37 Final.png",
    "game": "rbr",
    "name": "Season 37 Final",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "pink"
    ],
    "hex": "#54ddc4"
  },
  {
    "file": "lowres/rbr/Season 38 overview.png",
    "game": "rbr",
    "name": "Season 38 Overview",
    "color": "brown",
    "colors": [
      "brown",
      "pink",
      "blue"
    ],
    "hex": "#984a19"
  },
  {
    "file": "lowres/rbr/Season 41 (2).png",
    "game": "rbr",
    "name": "Season 41 (2)",
    "color": "brown",
    "colors": [
      "brown",
      "blue",
      "black"
    ],
    "hex": "#5b3559"
  },
  {
    "file": "lowres/rbr/Season 41.png",
    "game": "rbr",
    "name": "Season 41",
    "color": "orange",
    "colors": [
      "orange",
      "black",
      "white"
    ],
    "hex": "#d39f35"
  },
  {
    "file": "lowres/rbr/Season 42.png",
    "game": "rbr",
    "name": "Season 42",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "purple"
    ],
    "hex": "#291a45"
  },
  {
    "file": "lowres/rbr/Season 44-45 - natedrbr.png",
    "game": "rbr",
    "name": "Season 44 45 Natedrbr",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "orange"
    ],
    "hex": "#7e5409"
  },
  {
    "file": "lowres/rbr/Season 45.png",
    "game": "rbr",
    "name": "Season 45",
    "color": "brown",
    "colors": [
      "brown",
      "orange",
      "black"
    ],
    "hex": "#7b5407"
  },
  {
    "file": "lowres/rbr/Season28Video.png",
    "game": "rbr",
    "name": "Season28video",
    "color": "black",
    "colors": [
      "black",
      "teal",
      "gray"
    ],
    "hex": "#030908"
  },
  {
    "file": "lowres/rbr/Season36Thumbnail.png",
    "game": "rbr",
    "name": "Season36thumbnail",
    "color": "black",
    "colors": [
      "black",
      "purple",
      "brown"
    ],
    "hex": "#2b2b2b"
  },
  {
    "file": "lowres/rbr/Season37Thumbnail.png",
    "game": "rbr",
    "name": "Season37thumbnail",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "red"
    ],
    "hex": "#47c3f3"
  },
  {
    "file": "lowres/rbr/Seasonal video 46 (2).png",
    "game": "rbr",
    "name": "Seasonal Video 46 (2)",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#005e98"
  },
  {
    "file": "lowres/rbr/Seasonal video 46.png",
    "game": "rbr",
    "name": "Seasonal Video 46",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#0565aa"
  },
  {
    "file": "lowres/rbr/SecondVideo.png",
    "game": "rbr",
    "name": "Secondvideo",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "brown"
    ],
    "hex": "#fffffd"
  },
  {
    "file": "lowres/rbr/SHADOW-Look at me!.png",
    "game": "rbr",
    "name": "Shadow Look At Me!",
    "color": "black",
    "colors": [
      "black",
      "teal",
      "white"
    ],
    "hex": "#00563e"
  },
  {
    "file": "lowres/rbr/Shifty-Thumbnail.png",
    "game": "rbr",
    "name": "Shifty Thumbnail",
    "color": "pink",
    "colors": [
      "pink",
      "black",
      "brown"
    ],
    "hex": "#c99b70"
  },
  {
    "file": "lowres/rbr/Sirnukesalot-Nuketown.png",
    "game": "rbr",
    "name": "Sirnukesalot Nuketown",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "green"
    ],
    "hex": "#795934"
  },
  {
    "file": "lowres/rbr/slayer badges.png",
    "game": "rbr",
    "name": "Slayer Badges",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "red"
    ],
    "hex": "#00326a"
  },
  {
    "file": "lowres/rbr/Slippy dee-montage (2).png",
    "game": "rbr",
    "name": "Slippy Dee Montage (2)",
    "color": "black",
    "colors": [
      "black",
      "white",
      "teal"
    ],
    "hex": "#001417"
  },
  {
    "file": "lowres/rbr/Slippy dee-montage.png",
    "game": "rbr",
    "name": "Slippy Dee Montage",
    "color": "black",
    "colors": [
      "black",
      "white",
      "teal"
    ],
    "hex": "#000e0f"
  },
  {
    "file": "lowres/rbr/Slippy dee-Shottaflowmontage.png",
    "game": "rbr",
    "name": "Slippy Dee Shottaflowmontage",
    "color": "black",
    "colors": [
      "black",
      "teal",
      "white"
    ],
    "hex": "#001617"
  },
  {
    "file": "lowres/rbr/Sold Out Dates (updated).png",
    "game": "rbr",
    "name": "Sold Out Dates (updated)",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "gray"
    ],
    "hex": "#231e1a"
  },
  {
    "file": "lowres/rbr/Sold Out Dates.png",
    "game": "rbr",
    "name": "Sold Out Dates",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "gray"
    ],
    "hex": "#141311"
  },
  {
    "file": "lowres/rbr/Spacify-Birthday (2).png",
    "game": "rbr",
    "name": "Spacify Birthday (2)",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "blue"
    ],
    "hex": "#4d426b"
  },
  {
    "file": "lowres/rbr/Spacify-Birthday.png",
    "game": "rbr",
    "name": "Spacify Birthday",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "blue"
    ],
    "hex": "#44486f"
  },
  {
    "file": "lowres/rbr/Spacify-Wake Up F1lthy.png",
    "game": "rbr",
    "name": "Spacify Wake Up F1lthy",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "black"
    ],
    "hex": "#354258"
  },
  {
    "file": "lowres/rbr/SPG_Space-Fighting My Demons.png",
    "game": "rbr",
    "name": "Spg Space Fighting My Demons",
    "color": "white",
    "colors": [
      "white",
      "brown",
      "black"
    ],
    "hex": "#fdfbfb"
  },
  {
    "file": "lowres/rbr/stage light on white tank.png",
    "game": "rbr",
    "name": "Stage Light On White Tank",
    "color": "black",
    "colors": [
      "black",
      "white",
      "gray"
    ],
    "hex": "#0b0b0b"
  },
  {
    "file": "lowres/rbr/stick-community montage.png",
    "game": "rbr",
    "name": "Stick Community Montage",
    "color": "white",
    "colors": [
      "white",
      "red",
      "brown"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/switch games.png",
    "game": "rbr",
    "name": "Switch Games",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "gray"
    ],
    "hex": "#001d4d"
  },
  {
    "file": "lowres/rbr/TangoMangle-Skyfall.png",
    "game": "rbr",
    "name": "Tangomangle Skyfall",
    "color": "gray",
    "colors": [
      "gray",
      "white",
      "orange"
    ],
    "hex": "#907573"
  },
  {
    "file": "lowres/rbr/TaNk8k thumbnail.png",
    "game": "rbr",
    "name": "Tank8k Thumbnail",
    "color": "blue",
    "colors": [
      "blue",
      "brown",
      "white"
    ],
    "hex": "#55beda"
  },
  {
    "file": "lowres/rbr/TarasKhan and HSG - Versus.png",
    "game": "rbr",
    "name": "Taraskhan And Hsg Versus",
    "color": "teal",
    "colors": [
      "teal",
      "orange",
      "red"
    ],
    "hex": "#0f5a80"
  },
  {
    "file": "lowres/rbr/TarasKhan475-LOREEEEEE (2).png",
    "game": "rbr",
    "name": "Taraskhan475 Loreeeeee (2)",
    "color": "white",
    "colors": [
      "white",
      "gray",
      "black"
    ],
    "hex": "#fffffd"
  },
  {
    "file": "lowres/rbr/TarasKhan475-LOREEEEEE.png",
    "game": "rbr",
    "name": "Taraskhan475 Loreeeeee",
    "color": "white",
    "colors": [
      "white",
      "gray",
      "black"
    ],
    "hex": "#fffffe"
  },
  {
    "file": "lowres/rbr/TarasKhan475-RBR ripoff.png",
    "game": "rbr",
    "name": "Taraskhan475 Rbr Ripoff",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#0687c0"
  },
  {
    "file": "lowres/rbr/TarasKhan475-Season 39.png",
    "game": "rbr",
    "name": "Taraskhan475 Season 39",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#0c71a5"
  },
  {
    "file": "lowres/rbr/TarasKhan475-Season38(wrong).png",
    "game": "rbr",
    "name": "Taraskhan475 Season38(wrong)",
    "color": "brown",
    "colors": [
      "brown",
      "gray",
      "blue"
    ],
    "hex": "#974918"
  },
  {
    "file": "lowres/rbr/Tax Evasion-Falling Down (2).png",
    "game": "rbr",
    "name": "Tax Evasion Falling Down (2)",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#1f9bdf"
  },
  {
    "file": "lowres/rbr/Tax Evasion-Falling Down.png",
    "game": "rbr",
    "name": "Tax Evasion Falling Down",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "white"
    ],
    "hex": "#0b6ec1"
  },
  {
    "file": "lowres/rbr/Tax Evasion-Naturals.png",
    "game": "rbr",
    "name": "Tax Evasion Naturals",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "white"
    ],
    "hex": "#0f3e33"
  },
  {
    "file": "lowres/rbr/TaxEvasion-Naturals.png",
    "game": "rbr",
    "name": "Taxevasion Naturals",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "gray"
    ],
    "hex": "#040404"
  },
  {
    "file": "lowres/rbr/tertris piston tank montage.png",
    "game": "rbr",
    "name": "Tertris Piston Tank Montage",
    "color": "black",
    "colors": [
      "black",
      "gray",
      "blue"
    ],
    "hex": "#08002d"
  },
  {
    "file": "lowres/rbr/Tetris.png",
    "game": "rbr",
    "name": "Tetris",
    "color": "white",
    "colors": [
      "white",
      "black",
      "orange"
    ],
    "hex": "#f4f7ec"
  },
  {
    "file": "lowres/rbr/Thank you and Goodnight.png",
    "game": "rbr",
    "name": "Thank You And Goodnight",
    "color": "blue",
    "colors": [
      "blue",
      "brown",
      "black"
    ],
    "hex": "#53c5f0"
  },
  {
    "file": "lowres/rbr/Thumbnails.png",
    "game": "rbr",
    "name": "Thumbnails",
    "color": "white",
    "colors": [
      "white",
      "black",
      "blue"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/tools video rocket bot royale and goober dash.png",
    "game": "rbr",
    "name": "Tools Video Rocket Bot Royale And Goober Dash",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#0882bc"
  },
  {
    "file": "lowres/rbr/Top10RBR.png",
    "game": "rbr",
    "name": "Top10rbr",
    "color": "white",
    "colors": [
      "white",
      "brown",
      "orange"
    ],
    "hex": "#fffffe"
  },
  {
    "file": "lowres/rbr/tr1ck-Ganstas Paradise.png",
    "game": "rbr",
    "name": "Tr1ck Ganstas Paradise",
    "color": "white",
    "colors": [
      "white",
      "gray",
      "black"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/Tr1ck-Royalty.png",
    "game": "rbr",
    "name": "Tr1ck Royalty",
    "color": "yellow",
    "colors": [
      "yellow",
      "black",
      "blue"
    ],
    "hex": "#fabb0d"
  },
  {
    "file": "lowres/rbr/tr1ck-Ultimate Montage.png",
    "game": "rbr",
    "name": "Tr1ck Ultimate Montage",
    "color": "white",
    "colors": [
      "white",
      "red",
      "black"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/Trick-Don'tStopMeNow.png",
    "game": "rbr",
    "name": "Trick Don'tstopmenow",
    "color": "blue",
    "colors": [
      "blue",
      "white"
    ],
    "hex": "#0479c5"
  },
  {
    "file": "lowres/rbr/triple kill montage.png",
    "game": "rbr",
    "name": "Triple Kill Montage",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "yellow"
    ],
    "hex": "#023185"
  },
  {
    "file": "lowres/rbr/triplekill.png",
    "game": "rbr",
    "name": "Triplekill",
    "color": "blue",
    "colors": [
      "blue",
      "black",
      "yellow"
    ],
    "hex": "#023185"
  },
  {
    "file": "lowres/rbr/trolling noobs.png",
    "game": "rbr",
    "name": "Trolling Noobs",
    "color": "red",
    "colors": [
      "red",
      "white",
      "black"
    ],
    "hex": "#bb0000"
  },
  {
    "file": "lowres/rbr/underwater.png",
    "game": "rbr",
    "name": "Underwater",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#13507e"
  },
  {
    "file": "lowres/rbr/Unknown-Humble.png",
    "game": "rbr",
    "name": "Unknown Humble",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "green"
    ],
    "hex": "#93bedf"
  },
  {
    "file": "lowres/rbr/Untitled design (3).png",
    "game": "rbr",
    "name": "Untitled Design (3)",
    "color": "black",
    "colors": [
      "black",
      "white",
      "blue"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/Untitled Montage - hihiguys.png",
    "game": "rbr",
    "name": "Untitled Montage Hihiguys",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "brown"
    ],
    "hex": "#0886e2"
  },
  {
    "file": "lowres/rbr/Vedant-Avengers.png",
    "game": "rbr",
    "name": "Vedant Avengers",
    "color": "white",
    "colors": [
      "white",
      "teal",
      "black"
    ],
    "hex": "#fffefe"
  },
  {
    "file": "lowres/rbr/Vedant-Opening 2nd Elite Crates.png",
    "game": "rbr",
    "name": "Vedant Opening 2nd Elite Crates",
    "color": "orange",
    "colors": [
      "orange",
      "yellow",
      "white"
    ],
    "hex": "#c56803"
  },
  {
    "file": "lowres/rbr/Vedant-pfp.png",
    "game": "rbr",
    "name": "Vedant Pfp",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "gray"
    ],
    "hex": "#7b5d0f"
  },
  {
    "file": "lowres/rbr/versus 2.png",
    "game": "rbr",
    "name": "Versus 2",
    "color": "black",
    "colors": [
      "black",
      "red",
      "brown"
    ],
    "hex": "#4f005e"
  },
  {
    "file": "lowres/rbr/versus battle.png",
    "game": "rbr",
    "name": "Versus Battle",
    "color": "black",
    "colors": [
      "black",
      "red",
      "white"
    ],
    "hex": "#061867"
  },
  {
    "file": "lowres/rbr/versusthumbnail1.png",
    "game": "rbr",
    "name": "Versusthumbnail1",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "white"
    ],
    "hex": "#001e3e"
  },
  {
    "file": "lowres/rbr/versusthumbnail10.png",
    "game": "rbr",
    "name": "Versusthumbnail10",
    "color": "gray",
    "colors": [
      "gray",
      "black",
      "blue"
    ],
    "hex": "#7c6652"
  },
  {
    "file": "lowres/rbr/versusthumbnail11.png",
    "game": "rbr",
    "name": "Versusthumbnail11",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "white"
    ],
    "hex": "#001329"
  },
  {
    "file": "lowres/rbr/versusthumbnail12.png",
    "game": "rbr",
    "name": "Versusthumbnail12",
    "color": "black",
    "colors": [
      "black",
      "purple",
      "brown"
    ],
    "hex": "#0d2c26"
  },
  {
    "file": "lowres/rbr/versusthumbnail13.png",
    "game": "rbr",
    "name": "Versusthumbnail13",
    "color": "black",
    "colors": [
      "black",
      "white",
      "red"
    ],
    "hex": "#0a0821"
  },
  {
    "file": "lowres/rbr/versusthumbnail2.png",
    "game": "rbr",
    "name": "Versusthumbnail2",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "white"
    ],
    "hex": "#002d60"
  },
  {
    "file": "lowres/rbr/versusthumbnail3.png",
    "game": "rbr",
    "name": "Versusthumbnail3",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "red"
    ],
    "hex": "#00244a"
  },
  {
    "file": "lowres/rbr/versusthumbnail4.png",
    "game": "rbr",
    "name": "Versusthumbnail4",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "brown"
    ],
    "hex": "#002349"
  },
  {
    "file": "lowres/rbr/versusthumbnail5.png",
    "game": "rbr",
    "name": "Versusthumbnail5",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "brown"
    ],
    "hex": "#000000"
  },
  {
    "file": "lowres/rbr/versusthumbnail6.png",
    "game": "rbr",
    "name": "Versusthumbnail6",
    "color": "black",
    "colors": [
      "black",
      "brown",
      "gray"
    ],
    "hex": "#144061"
  },
  {
    "file": "lowres/rbr/versusthumbnail7.png",
    "game": "rbr",
    "name": "Versusthumbnail7",
    "color": "black",
    "colors": [
      "black",
      "gray",
      "teal"
    ],
    "hex": "#352d6b"
  },
  {
    "file": "lowres/rbr/versusthumbnail8.png",
    "game": "rbr",
    "name": "Versusthumbnail8",
    "color": "black",
    "colors": [
      "black",
      "teal",
      "brown"
    ],
    "hex": "#362e41"
  },
  {
    "file": "lowres/rbr/versusthumbnail9.png",
    "game": "rbr",
    "name": "Versusthumbnail9",
    "color": "black",
    "colors": [
      "black",
      "teal",
      "brown"
    ],
    "hex": "#362e3e"
  },
  {
    "file": "lowres/rbr/Wam101-montage.png",
    "game": "rbr",
    "name": "Wam101 Montage",
    "color": "brown",
    "colors": [
      "brown",
      "black",
      "white"
    ],
    "hex": "#660b0b"
  },
  {
    "file": "lowres/rbr/WeaponStrategy.png",
    "game": "rbr",
    "name": "Weaponstrategy",
    "color": "black",
    "colors": [
      "black",
      "blue",
      "gray"
    ],
    "hex": "#002d61"
  },
  {
    "file": "lowres/rbr/what your tank says about you.png",
    "game": "rbr",
    "name": "What Your Tank Says About You",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "brown"
    ],
    "hex": "#3679fa"
  },
  {
    "file": "lowres/rbr/who is better.png",
    "game": "rbr",
    "name": "Who Is Better",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "black"
    ],
    "hex": "#fbfdfd"
  },
  {
    "file": "lowres/rbr/winterpixel community.png",
    "game": "rbr",
    "name": "Winterpixel Community",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "black"
    ],
    "hex": "#fcffff"
  },
  {
    "file": "lowres/rbr/winterpixel montage.png",
    "game": "rbr",
    "name": "Winterpixel Montage",
    "color": "white",
    "colors": [
      "white",
      "blue",
      "gray"
    ],
    "hex": "#ffffff"
  },
  {
    "file": "lowres/rbr/WinterpixelCheatsThumbnail.png",
    "game": "rbr",
    "name": "Winterpixelcheatsthumbnail",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#0585c1"
  },
  {
    "file": "lowres/rbr/wood crown badge beta.png",
    "game": "rbr",
    "name": "Wood Crown Badge Beta",
    "color": "brown",
    "colors": [
      "brown",
      "black"
    ],
    "hex": "#5d442f"
  },
  {
    "file": "lowres/rbr/Youtube Thumbnails (2).png",
    "game": "rbr",
    "name": "Youtube Thumbnails (2)",
    "color": "brown",
    "colors": [
      "brown",
      "white",
      "green"
    ],
    "hex": "#8e502a"
  },
  {
    "file": "lowres/rbr/Yoyble-Bruuuh.png",
    "game": "rbr",
    "name": "Yoyble Bruuuh",
    "color": "blue",
    "colors": [
      "blue",
      "white",
      "black"
    ],
    "hex": "#0f72b0"
  },
  {
    "file": "lowres/rbr/YTSiuu-If We Being Real.png",
    "game": "rbr",
    "name": "Ytsiuu If We Being Real",
    "color": "black",
    "colors": [
      "black",
      "gray",
      "brown"
    ],
    "hex": "#000000"
  }
];
